<?php

namespace App\Console\Commands;

use App\Models\Role;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Permission;

class DeleteConcreteModuleCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * app:delete-module Post Admin
     * app:delete-module Post Admin --with-migration
     * app:delete-module Post Admin --force
     *
     * @var string
     */
    protected $signature = 'app:delete-module {modelName} {namespace} {--with-migration} {--force}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Delete a module previously generated by app:generate-module (model, resource, request, contract, concrete, controller, permissions, optionally the migration)';

    public function handle()
    {
        $namespace = $this->argument('namespace');
        $modelName = ucfirst(Str::camel($this->argument('modelName')));

        if (!$this->option('force') && !$this->confirm("This will permanently delete all generated files for [{$modelName}]. Continue?")) {
            $this->warn('Aborted.');
            return;
        }

        $this->deleteModel($modelName);
        $this->deleteResource($modelName, $namespace);
        $this->deleteRequest($modelName, $namespace);
        $this->deleteContract($modelName);
        $this->deleteConcrete($modelName);
        $this->deleteController($modelName, $namespace);
        $this->removeModelFromPermissions($modelName);

        if ($this->option('with-migration')) {
            $this->deleteMigration($modelName);
        } else {
            $this->comment('Skipped migration file (pass --with-migration to delete it too).');
        }

        $this->info('Module ' . $modelName . ' deleted successfully');
    }

    protected function deleteFile(string $path, string $label): void
    {
        if (File::exists($path)) {
            File::delete($path);
            $this->info($label . ' deleted: ' . $path);
        } else {
            $this->warn($label . ' not found: ' . $path);
        }
    }

    public function deleteModel($modelName): void
    {
        $path = app_path('Models' . DIRECTORY_SEPARATOR . $modelName . '.php');
        $this->deleteFile($path, 'Model');
    }

    public function deleteResource($modelName, $namespace): void
    {
        $path = app_path('Http/Resources/' . $namespace . DIRECTORY_SEPARATOR . $modelName . 'Resource.php');
        $this->deleteFile($path, 'Resource');
    }

    public function deleteRequest($modelName, $namespace): void
    {
        $path = app_path('Http/Requests/' . $namespace . DIRECTORY_SEPARATOR . $modelName . 'Request.php');
        $this->deleteFile($path, 'Request');
    }

    public function deleteContract($modelName): void
    {
        $path = app_path('Repositories/Contracts' . DIRECTORY_SEPARATOR . $modelName . 'Contract.php');
        $this->deleteFile($path, 'Contract');
    }

    public function deleteConcrete($modelName): void
    {
        $path = app_path('Repositories/Concretes' . DIRECTORY_SEPARATOR . $modelName . 'Concrete.php');
        $this->deleteFile($path, 'Concrete');
    }

    public function deleteController($modelName, $namespace): void
    {
        $path = app_path('Http/Controllers/' . $namespace . DIRECTORY_SEPARATOR . $modelName . 'Controller.php');
        $this->deleteFile($path, 'Controller');
    }

    public function deleteMigration($modelName): void
    {
        $tableName = Str::plural(lcfirst($modelName));
        $migrations = File::glob(database_path('migrations/*_create_' . $tableName . '_table.php'));

        if (empty($migrations)) {
            $this->warn('No migration found for table: ' . $tableName);
            return;
        }

        foreach ($migrations as $migration) {
            File::delete($migration);
            $this->info('Migration deleted: ' . $migration);
        }

        $this->comment("Note: this only deletes the migration file. If the table [{$tableName}] already exists in the database, run a rollback or drop it manually.");
    }

    /**
     * Reverses addModelToPermissions(): removes the permissions the generator
     * created for this model from the admin role and from the language files.
     *
     * IMPORTANT: this assumes RolesPermissionGenerator names permissions using
     * the plural model name (e.g. "posts"). Check that class if your naming
     * pattern differs (e.g. "index-posts", "posts.index", etc.) and adjust the
     * `where('name', 'like', ...)` clause below accordingly.
     */
    private function removeModelFromPermissions($modelName): void
    {
        $permissionKey = Str::plural(lcfirst($modelName));

        $permissions = Permission::where('guard_name', 'api')
            ->where('name', 'like', '%' . $permissionKey . '%')
            ->get();

        if ($permissions->isEmpty()) {
            $this->warn('No permissions found matching: ' . $permissionKey);
        } else {
            foreach ($permissions as $permission) {
                $permission->roles()->detach();
                $permission->delete();
                $this->info('Permission deleted: ' . $permission->name);
            }
        }

        foreach (['en', 'ar'] as $locale) {
            $filePath = base_path('lang/' . $locale . '/permissions.php');

            if (!File::exists($filePath)) {
                continue;
            }

            $permissionsArr = require $filePath;

            if (isset($permissionsArr['responses'][$permissionKey])) {
                unset($permissionsArr['responses'][$permissionKey]);
                File::put($filePath, '<?php return ' . var_export($permissionsArr, true) . ';');
                $this->info("Removed '{$permissionKey}' from lang/{$locale}/permissions.php");
            }
        }
    }
}
